# Generated by Django 5.1.6 on 2025-03-31 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='crop_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='CropModelMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_path', models.CharField(max_length=255)),
                ('crop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model_mapping', to='crops.crop')),
            ],
        ),
    ]
