# Generated by Django 5.1.6 on 2025-02-21 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropvariable',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='cropvariable',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
