# Generated by Django 5.1.6 on 2025-04-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_alter_crop_crop_image_cropmodelmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='care_tips',
            field=models.TextField(blank=True, help_text='เคล็ดลับการดูแลรักษา', null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='cultivation_method',
            field=models.TextField(blank=True, help_text='วิธีการเพาะปลูกและดูแลรักษา', null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='ideal_soil',
            field=models.TextField(blank=True, help_text='ข้อมูลดินที่เหมาะสม', null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='optimal_season',
            field=models.TextField(blank=True, help_text='ฤดูกาลที่เหมาะสมในการปลูก', null=True),
        ),
    ]
