# Generated by Django 5.1.6 on 2025-02-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_remove_cropvariable_timestamp_cropvariable_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropvariable',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
