# Generated by Django 5.1.6 on 2025-04-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_crop_care_tips_crop_cultivation_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='grow_duration',
            field=models.CharField(help_text='ระยะเวลาปลูก (วัน)', max_length=50),
        ),
    ]
