# Generated by Django 5.1.6 on 2025-04-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0004_alter_crop_grow_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='grow_duration',
        ),
        migrations.AddField(
            model_name='crop',
            name='max_growth_duration',
            field=models.IntegerField(default=60, help_text='ระยะเวลาปลูกสูงสุด (วัน)'),
        ),
        migrations.AddField(
            model_name='crop',
            name='min_growth_duration',
            field=models.IntegerField(default=30, help_text='ระยะเวลาปลูกขั้นต่ำ (วัน)'),
        ),
    ]
