# Generated by Django 5.1.6 on 2025-04-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0005_remove_crop_grow_duration_crop_max_growth_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='crop_image',
            field=models.ImageField(blank=True, null=True, upload_to='crop_images/'),
        ),
    ]
