# Generated by Django 5.1.6 on 2025-04-28 19:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0006_alter_crop_crop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='crop_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
